version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub actions once a week
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      # Check for updates to submodules every month
      interval: "monthly"
