name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  # Path to the solution file relative to the root of the project.
  solution_file: PapyrusPlugin.sln

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
        platform: [x64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Run git diff check
        run: |
          git config --global core.whitespace cr-at-eol,tab-in-indent
          git diff --check HEAD^ ':!.gitmodules' ':!*.sln' ':!dist/extras' ':!src/external'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Update build number
        working-directory: ${{ github.workspace }}\src\Plugin\Common
        run: (gc Resources.hpp) -replace 'BUILD_NUMBER    0', 'BUILD_NUMBER    ${{ github.run_number }}' | Out-File -encoding ASCII Resources.hpp

      - name: Build plugin DLL
        run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{ env.solution_file }}
